package org.scriptdojo.backend.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * JPA entity representing a collaboration room in ScriptDojo.
 * A room is a lightweight join record that links a shareable alphanumeric ID
 * to a specific file and its host. It is created when a host clicks "Share"
 * on a file and persists until manually deleted (rooms are not currently
 * expired or cleaned up automatically).
 * Unlike most entities in the application, the primary key is a
 * human-generated string (an 11-character alphanumeric ID produced by
 * rather than a database auto-increment value. This ID forms the path segment
 * of the shareable URL (e.g. /room/abc123xyz89) and is safe to expose publicly.
 * Relationships are stored as plain foreign key columns (fileId, hostId) rather
 * than @ManyToOne associations to keep the entity lightweight — neither the file
 * nor the host entity is navigated to from a room record directly.
 * Note: Lombok is not used here — accessors and constructors are written
 * explicitly. Maps to the "rooms" table in the database.
 */
@Entity
@Table(name = "rooms")
public class RoomEntity {

    /**
     * The shareable room identifier — an 11-character alphanumeric string
     * generated by RoomController at room creation time.
     * Forms the path segment of the guest invite URL: /room/{id}.
     * Not auto-generated by the database; set explicitly before persistence.
     */
    @Id
    private String id;

    /**
     * The ID of the file being shared in this room.
     * Used by the join endpoint to load the file content for incoming guests.
     * Stored as a plain column rather than a @ManyToOne to avoid eagerly
     * loading the FileEntity whenever a room is looked up.
     * Must not be null.
     */
    @Column(name = "file_id", nullable = false)
    private Long fileId;

    /**
     * The user ID of the host who created this room.
     * Recorded for auditing and to support future host-only operations
     * (e.g. closing a room or transferring ownership).
     * Stored as a plain column rather than a @ManyToOne for the same
     * reason as fileId. Must not be null.
     */
    @Column(name = "host_id", nullable = false)
    private Long hostId;

    /**
     * The timestamp at which this room was created.
     * Initialised to the current time in both constructors and never
     * subsequently modified — rooms do not currently track update times.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * No-argument constructor required by the JPA specification.
     * JPA instantiates entities via reflection using this constructor
     * when loading records from the database.
     */
    public RoomEntity() {
    }

    /**
     * Convenience constructor for programmatic room creation.
     * Used by {@link org.scriptdojo.backend.controller.RoomController}
     * when a host creates a new room.
     * @param id     the pre-generated alphanumeric room ID
     * @param fileId the ID of the file being shared
     * @param hostId the user ID of the host creating the room
     */
    public RoomEntity(String id, Long fileId, Long hostId) {
        this.id = id;
        this.fileId = fileId;
        this.hostId = hostId;
        this.createdAt = LocalDateTime.now();
    }

    // ─ Getters and setters

    /** Returns the shareable room ID. */
    public String getId() {
        return id;
    }

    /** Sets the room ID. Should only be called before the entity is first persisted. */
    public void setId(String id) {
        this.id = id;
    }

    /** Returns the ID of the file associated with this room. */
    public Long getFileId() {
        return fileId;
    }

    /** Sets the file ID. */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /** Returns the user ID of the host who created this room. */
    public Long getHostId() {
        return hostId;
    }

    /** Sets the host user ID. */
    public void setHostId(Long hostId) {
        this.hostId = hostId;
    }

    /** Returns the timestamp at which this room was created. */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** Sets the creation timestamp. Required by JPA for entity hydration. */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}